# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate codepage-strings
%global source_sha256 96e0dcc0fce1af8fe139537bcd0c2522296a701bf11eb6b143ca88ff8c742523

Name:           rust-codepage-strings1
Version:        1.0.2
Release:        0.1%{?dist}
Summary:        Encode / decode strings for Windows code pages

License:        MIT
URL:            https://crates.io/crates/codepage-strings
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Encode / decode strings for Windows code pages.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 1.0.2-0.1
- Add the initial repository packaging changelog.
