# Generated with rust2rpm 28 and reviewed by Marcin FM.
%bcond check 1
%global debug_package %{nil}
%global crate dirs-sys
%global source_sha256 520f05a5cbd335fae5a99ff7a6ab8627577660ee5cfd6a94a6a929b52ff0321c

Name:           rust-dirs-sys0.4
Version:        0.4.1
Release:        0.2%{?dist}
Summary:        System-level directory helpers for Rust applications

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/dirs-sys
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Generated by rust2rpm to remove non-Fedora target dependencies.
Patch0:         dirs-sys-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
System-level helper functions used by the dirs and directories Rust crates.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building Rust packages that
use the dirs-sys crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source for the default feature of dirs-sys.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.4.1-0.2
- Expand COPR targets to Fedora 44 and Rawhide on x86_64 and aarch64.

* Wed Jul 15 2026 Marcin FM <marcin@lgic.pl> - 0.4.1-0.1
- Add the Fedora 44 compatibility crate required by RTK.
