# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate entities
%global source_sha256 b5320ae4c3782150d900b79807611a59a99fc9a1d61d686faafc24b93fc8d7ca

Name:           rust-entities1
Version:        1.0.1
Release:        0.2%{?dist}
Summary:        Raw data needed to convert to and from HTML entities

License:        MIT
URL:            https://crates.io/crates/entities
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Provides the raw data needed to convert to and from HTML entities.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 1.0.1-0.2
- Enable the independently eligible leaf for six-cell SCM COPR publication.
- Use the immutable static crates.io archive for source generation.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 1.0.1-0.1
- Add the initial repository packaging changelog.
