# Generated by rust2rpm 28; provisionally adapted for Fedora polyclipping.
%bcond check 1
%global debug_package %{nil}

%global crate clipper-sys
%global source_sha256 b5141c32419064aef7322f754b92fd4ea53c360c1ad984ec38b58af533eba3ac

Name:           rust-clipper-sys
Version:        0.8.0
Release:        0.1%{?dist}
Summary:        Boolean operations on polygons (Clipper wrapper)

License:        ISC
URL:            https://crates.io/crates/clipper-sys
Source:         %{crates_source}
Patch0:         clipper-sys-0.8.0-system-polyclipping.patch
Patch1:         clipper-sys-0.8.0-fix-test-lifetimes.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gcc-c++
BuildRequires:  pkgconfig(polyclipping) >= 6.4.2

%global _description %{expand:
Boolean operations on polygons (Clipper wrapper).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(polyclipping) >= 6.4.2

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+generate-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+generate-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "generate-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+generate-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+update-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+update-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "update-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+update-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
# Do not ship the unbundled Clipper implementation or its BSL license payload.
rm -f %{buildroot}%{crate_instdir}/clipper/clipper.cpp
rm -f %{buildroot}%{crate_instdir}/clipper/clipper.hpp
rm -f %{buildroot}%{crate_instdir}/clipper/LICENSE.txt

%if %{with check}
%check
# This runs all seven upstream crate tests in the later isolated mock build.
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.8.0-0.1
- Add the initial repository packaging changelog.
%autochangelog
