# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate utf16string
%global source_sha256 0b62a1e85e12d5d712bf47a85f426b73d303e2d00a90de5f3004df3596e9d216

Name:           rust-utf16string0.2
Version:        0.2.0
Release:        0.5%{?dist}
Summary:        String types to work directly with UTF-16 encoded strings

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/utf16string
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
String types to work directly with UTF-16 encoded strings.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.5
- Include Rawhide where Kreuzberg consumes this dependency.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.4
- Use the immutable static crates.io archive for SCM source generation.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.3
- Enable the independently eligible leaf crate for SCM COPR publication.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.2
- Record current four-chroot build and artifact-lint proof for the leaf crate.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.1
- Add the initial repository packaging changelog.
