# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate serde_yaml_ng
%global source_sha256 7b4db627b98b36d4203a7b458cf3573730f2bb591b28871d916dfa9efabfd41f

Name:           rust-serde_yaml_ng0.10
Version:        0.10.0
Release:        0.2%{?dist}
Summary:        YAML data format for Serde

License:        MIT
URL:            https://crates.io/crates/serde_yaml_ng
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
YAML data format for Serde.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.10.0-0.2
- Enable configured SCM publication from the immutable crates.io source.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.10.0-0.1
- Add the initial repository packaging changelog.
