# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate maybe-owned
%global source_sha256 4facc753ae494aeb6e3c22f839b158aebd4f9270f55cd3c79906c45476c47ab4

Name:           rust-maybe-owned0.3
Version:        0.3.4
Release:        0.1%{?dist}
Summary:        MaybeOwned

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/maybe-owned
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Provides a `MaybeOwned` (and `MaybeOwnedMut`) type similar to `Cow` from the
Rust standard library. It implements `From<T>` and `From<&'a T>` without
requiring `ToOwned`.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.3.4-0.1
- Clarify the Rust standard-library reference in package metadata.
