# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate text-splitter
%global source_sha256 3f3eeec76988617ff1434d754d7e8e197be2cb8981ea77c17e32f3f7a2c6f95e

Name:           rust-text-splitter0.32
Version:        0.32.0
Release:        0.2%{?dist}
Summary:        Split text into semantic chunks, up to a desired chunk size

License:        MIT
URL:            https://crates.io/crates/text-splitter
# crates.io release archive for the exact published crate.
Source:         https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora carries tokenizers 0.22.2; this narrows the compatible dependency branch without changing the selected API.
# Fedora-specific compatibility adjustment; not submitted because upstream intentionally moved to tokenizers 0.23.
Patch:          text-splitter-fedora-tokenizers.diff
# The published crate omits integration fixtures and some unit tests require network-fetched models.
# Fedora-specific offline test reduction; not submitted because upstream intentionally tests the complete repository checkout.
Patch:          text-splitter-fedora-tests.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Split text into semantic chunks, up to a desired chunk size. Supports
calculating length by characters and tokens, and is callable from Rust
and Python.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+code-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+code-devel %{_description}

This package contains library source intended for building other packages which
use the "code" feature of the "%{crate}" crate.

%files       -n %{name}+code-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+markdown-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+markdown-devel %{_description}

This package contains library source intended for building other packages which
use the "markdown" feature of the "%{crate}" crate.

%files       -n %{name}+markdown-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tiktoken-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tiktoken-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "tiktoken-rs" feature of the "%{crate}" crate.

%files       -n %{name}+tiktoken-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokenizers-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokenizers-devel %{_description}

This package contains library source intended for building other packages which
use the "tokenizers" feature of the "%{crate}" crate.

%files       -n %{name}+tokenizers-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f code,markdown,tokenizers

%build
%cargo_build -f code,markdown,tokenizers

%install
%cargo_install -f code,markdown,tokenizers

%if %{with check}
%check
%cargo_test -f code,markdown,tokenizers -- --lib
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 0.32.0-0.2
- Enable the fixture-free Fedora feature and test surface.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 0.32.0-0.1
- Build text-splitter 0.32.0 with Fedora tokenizers compatibility
- Retain inline tests and omit only unpublished fixture/snapshot tests
