# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate napi-sys
%global source_sha256 1f5bcdf71abd3a50d00b49c1c2c75251cb3c913777d6139cd37dabc093a5e400
%global license_commit dea608eae7481a47d64aab563a2ab5cdd8eda03c
%global license_sha256 3f1ce66533302df3a32edbfdfc0b78f0dd34659e4c1f5817162e5ea3c2297215

Name:           rust-napi-sys3
Version:        3.2.2
Release:        0.3%{?dist}
Summary:        NodeJS N-API raw binding

License:        MIT
URL:            https://crates.io/crates/napi-sys
Source:         %{crates_source}
Source1:        https://raw.githubusercontent.com/napi-rs/napi-rs/%{license_commit}/LICENSE#/napi-rs-LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
NodeJS N-API raw binding.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dyn-symbols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dyn-symbols-devel %{_description}

This package contains library source intended for building other packages which
use the "dyn-symbols" feature of the "%{crate}" crate.

%files       -n %{name}+dyn-symbols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+experimental-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+experimental-devel %{_description}

This package contains library source intended for building other packages which
use the "experimental" feature of the "%{crate}" crate.

%files       -n %{name}+experimental-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi1-devel %{_description}

This package contains library source intended for building other packages which
use the "napi1" feature of the "%{crate}" crate.

%files       -n %{name}+napi1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi10-devel %{_description}

This package contains library source intended for building other packages which
use the "napi10" feature of the "%{crate}" crate.

%files       -n %{name}+napi10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi2-devel %{_description}

This package contains library source intended for building other packages which
use the "napi2" feature of the "%{crate}" crate.

%files       -n %{name}+napi2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi3-devel %{_description}

This package contains library source intended for building other packages which
use the "napi3" feature of the "%{crate}" crate.

%files       -n %{name}+napi3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi4-devel %{_description}

This package contains library source intended for building other packages which
use the "napi4" feature of the "%{crate}" crate.

%files       -n %{name}+napi4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi5-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi5-devel %{_description}

This package contains library source intended for building other packages which
use the "napi5" feature of the "%{crate}" crate.

%files       -n %{name}+napi5-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi6-devel %{_description}

This package contains library source intended for building other packages which
use the "napi6" feature of the "%{crate}" crate.

%files       -n %{name}+napi6-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi7-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi7-devel %{_description}

This package contains library source intended for building other packages which
use the "napi7" feature of the "%{crate}" crate.

%files       -n %{name}+napi7-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi8-devel %{_description}

This package contains library source intended for building other packages which
use the "napi8" feature of the "%{crate}" crate.

%files       -n %{name}+napi8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi9-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi9-devel %{_description}

This package contains library source intended for building other packages which
use the "napi9" feature of the "%{crate}" crate.

%files       -n %{name}+napi9-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm 0644 %{SOURCE1} LICENSE-MIT
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -pm 0644 LICENSE-MIT %{buildroot}%{crate_instdir}/LICENSE-MIT

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 3.2.2-0.3
- Preserve the supplemental MIT license with the crate's explicit include list.

* Thu Jul 16 2026 OpenCode <noreply@example.invalid> - 3.2.2-0.2
- Install the pinned upstream MIT license omitted from the published crate.
