# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate cfb
%global source_sha256 d38f2da7a0a2c4ccf0065be06397cc26a81f4e528be095826eee9d4adbb8c60f

Name:           rust-cfb0.7
Version:        0.7.3
Release:        0.1%{?dist}
Summary:        Read/write Compound File Binary (structured storage) files

License:        MIT
URL:            https://crates.io/crates/cfb
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Read/write Compound File Binary (structured storage) files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.7.3-0.1
- Add the initial repository packaging changelog.
