status: enabled
name: rust-lopdf0.44
blockers: []
upstream:
  provider: crates_io
  crate: lopdf
  version_requirement: = 0.44.0
  current_version: 0.44.0
  source_url_template: https://static.crates.io/crates/lopdf/lopdf-{version}.crate
  source_sha256: 5e2ec995d822e05cabc3f06d196ee43650af3fe4fe38012cacb35e0c3d113b68
copr:
  enabled: true
  subdir: packages/rust-lopdf0.44
  spec: rust-lopdf0.44.spec
