# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate lopdf
%global source_sha256 5e2ec995d822e05cabc3f06d196ee43650af3fe4fe38012cacb35e0c3d113b68

Name:           rust-lopdf0.44
Version:        0.44.0
Release:        0.3%{?dist}
Summary:        Rust library for PDF document manipulation

License:        MIT
URL:            https://crates.io/crates/lopdf
Source:         https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Remove unselected benchmark and WebAssembly test dependencies from Fedora's native test graph.
# Fedora-specific; not submitted because upstream intentionally retains those development surfaces.
Patch:          lopdf-fix-metadata.diff
# Fix the default time feature against released time 0.3 APIs.
# Backport of upstream commit 1efa270266b97bcdc1f77d679351c064fb88bc1b.
Patch1:         0001-fix-make-the-time-feature-compile.patch
# Use Fedora time 0.3.47's supported format-description grammar version.
# Fedora-specific follow-up to the upstream fix; not yet submitted upstream.
Patch2:         lopdf-time-0.3.47-fedora.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A Rust library for PDF document manipulation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+embed_image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+embed_image-devel %{_description}

This package contains library source intended for building other packages which
use the "embed_image" feature of the "%{crate}" crate.

%files       -n %{name}+embed_image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+font_embedding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+font_embedding-devel %{_description}

This package contains library source intended for building other packages which
use the "font_embedding" feature of the "%{crate}" crate.

%files       -n %{name}+font_embedding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jiff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jiff-devel %{_description}

This package contains library source intended for building other packages which
use the "jiff" feature of the "%{crate}" crate.

%files       -n %{name}+jiff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm_js-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm_js-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm_js" feature of the "%{crate}" crate.

%files       -n %{name}+wasm_js-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n -f chrono,jiff,rayon,time

%build
%cargo_build -n -f chrono,jiff,rayon,time

%install
%cargo_install -n -f chrono,jiff,rayon,time

%if %{with check}
%check
%cargo_test -n -f chrono,jiff,rayon,time -- --test catalog_compression_integration_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test decompression_bomb
%cargo_test -n -f chrono,jiff,rayon,time -- --test extract_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test linearized_objstm_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test object_stream_comprehensive_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test object_stream_edge_cases_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test object_stream_methods_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test object_stream_performance_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test page_content
%cargo_test -n -f chrono,jiff,rayon,time -- --test simple_object_stream_test
%cargo_test -n -f chrono,jiff,rayon,time -- --test trailer_reference_compression_test
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 0.44.0-0.3
- Preserve the default feature tuple with asset-free integration tests.
- Backport the upstream time fix with Fedora's supported parser grammar.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 0.44.0-0.2
- Restore the immutable upstream test assets and retained time compatibility patch.
