# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate lopdf
%global source_sha256 5e2ec995d822e05cabc3f06d196ee43650af3fe4fe38012cacb35e0c3d113b68
%global fixtures_commit 8c454dd93d9c37e608c552a2b304d1d31d1cb2e1
%global fixtures_sha256 96bf4d0b73a173e54fa1bd4626b088c0fef9d7c141f63183e68c2d5098591532
%global test_pdf_sha256 1c814572e0ea8024811c83b063e707f711a8fd48373a53de7f7234a4fcf49663

Name:           rust-lopdf0.44
Version:        0.44.0
Release:        0.2%{?dist}
Summary:        Rust library for PDF document manipulation

License:        MIT
URL:            https://crates.io/crates/lopdf
Source:         %{crates_source}
Source1:        https://github.com/J-F-Liu/lopdf/archive/%{fixtures_commit}/lopdf-%{fixtures_commit}.tar.gz#/lopdf-test-assets.tar.gz
Source2:        lopdf-test.pdf
Patch:          lopdf-fix-metadata.diff
Patch1:         lopdf-time-0.3.47-compat.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A Rust library for PDF document manipulation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+embed_image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+embed_image-devel %{_description}

This package contains library source intended for building other packages which
use the "embed_image" feature of the "%{crate}" crate.

%files       -n %{name}+embed_image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+font_embedding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+font_embedding-devel %{_description}

This package contains library source intended for building other packages which
use the "font_embedding" feature of the "%{crate}" crate.

%files       -n %{name}+font_embedding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jiff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jiff-devel %{_description}

This package contains library source intended for building other packages which
use the "jiff" feature of the "%{crate}" crate.

%files       -n %{name}+jiff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm_js-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm_js-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm_js" feature of the "%{crate}" crate.

%files       -n %{name}+wasm_js-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{fixtures_sha256}  %{SOURCE1}" | sha256sum -c -
echo "%{test_pdf_sha256}  %{SOURCE2}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
tar -xzf %{SOURCE1} --strip-components=1 "lopdf-%{fixtures_commit}/assets"
cp -p %{SOURCE2} assets/test.pdf
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 0.44.0-0.2
- Restore the immutable upstream test assets and retained time compatibility patch.
