# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate napi
%global source_sha256 0c71997d6f7ad4a756966e452426848ac27d3b37a295302d63afbbcce0270f93
%global license_commit 1ac467e06e71f78b983630926c7908894d08e496
%global license_sha256 3f1ce66533302df3a32edbfdfc0b78f0dd34659e4c1f5817162e5ea3c2297215

Name:           rust-napi3
Version:        3.10.3
Release:        0.3%{?dist}
Summary:        N-API bindings

License:        MIT
URL:            https://crates.io/crates/napi
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
Source1:        https://raw.githubusercontent.com/napi-rs/napi-rs/%{license_commit}/LICENSE#/%{crate}-%{version}-LICENSE
# Fedora-only compatibility repair; upstream release 3.10.3 requires ctor 1 while Fedora supplies ctor 0.6.3.
Patch0:         napi-ctor0.6.diff
# Fedora-only target cleanup; the removed dependency is selected only for WASM, while this package targets Fedora Linux.
Patch1:         napi-no-wasm-tokio.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
N-API bindings.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono_date-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono_date-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono_date" feature of the "%{crate}" crate.

%files       -n %{name}+chrono_date-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compat-mode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compat-mode-devel %{_description}

This package contains library source intended for building other packages which
use the "compat-mode" feature of the "%{crate}" crate.

%files       -n %{name}+compat-mode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deferred_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deferred_trace-devel %{_description}

This package contains library source intended for building other packages which
use the "deferred_trace" feature of the "%{crate}" crate.

%files       -n %{name}+deferred_trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dyn-symbols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dyn-symbols-devel %{_description}

This package contains library source intended for building other packages which
use the "dyn-symbols" feature of the "%{crate}" crate.

%files       -n %{name}+dyn-symbols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding_rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding_rs-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding_rs" feature of the "%{crate}" crate.

%files       -n %{name}+encoding_rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+error_anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+error_anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "error_anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+error_anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+experimental-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+experimental-devel %{_description}

This package contains library source intended for building other packages which
use the "experimental" feature of the "%{crate}" crate.

%files       -n %{name}+experimental-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-core" feature of the "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+indexmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+indexmap-devel %{_description}

This package contains library source intended for building other packages which
use the "indexmap" feature of the "%{crate}" crate.

%files       -n %{name}+indexmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+latin1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+latin1-devel %{_description}

This package contains library source intended for building other packages which
use the "latin1" feature of the "%{crate}" crate.

%files       -n %{name}+latin1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi1-devel %{_description}

This package contains library source intended for building other packages which
use the "napi1" feature of the "%{crate}" crate.

%files       -n %{name}+napi1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi10-devel %{_description}

This package contains library source intended for building other packages which
use the "napi10" feature of the "%{crate}" crate.

%files       -n %{name}+napi10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi2-devel %{_description}

This package contains library source intended for building other packages which
use the "napi2" feature of the "%{crate}" crate.

%files       -n %{name}+napi2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi3-devel %{_description}

This package contains library source intended for building other packages which
use the "napi3" feature of the "%{crate}" crate.

%files       -n %{name}+napi3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi4-devel %{_description}

This package contains library source intended for building other packages which
use the "napi4" feature of the "%{crate}" crate.

%files       -n %{name}+napi4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi5-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi5-devel %{_description}

This package contains library source intended for building other packages which
use the "napi5" feature of the "%{crate}" crate.

%files       -n %{name}+napi5-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi6-devel %{_description}

This package contains library source intended for building other packages which
use the "napi6" feature of the "%{crate}" crate.

%files       -n %{name}+napi6-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi7-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi7-devel %{_description}

This package contains library source intended for building other packages which
use the "napi7" feature of the "%{crate}" crate.

%files       -n %{name}+napi7-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi8-devel %{_description}

This package contains library source intended for building other packages which
use the "napi8" feature of the "%{crate}" crate.

%files       -n %{name}+napi8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+napi9-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+napi9-devel %{_description}

This package contains library source intended for building other packages which
use the "napi9" feature of the "%{crate}" crate.

%files       -n %{name}+napi9-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+node_version_detect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+node_version_detect-devel %{_description}

This package contains library source intended for building other packages which
use the "node_version_detect" feature of the "%{crate}" crate.

%files       -n %{name}+node_version_detect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+noop-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+noop-devel %{_description}

This package contains library source intended for building other packages which
use the "noop" feature of the "%{crate}" crate.

%files       -n %{name}+noop-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+object_indexmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+object_indexmap-devel %{_description}

This package contains library source intended for building other packages which
use the "object_indexmap" feature of the "%{crate}" crate.

%files       -n %{name}+object_indexmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde-json" feature of the "%{crate}" crate.

%files       -n %{name}+serde-json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-json-ordered-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-json-ordered-devel %{_description}

This package contains library source intended for building other packages which
use the "serde-json-ordered" feature of the "%{crate}" crate.

%files       -n %{name}+serde-json-ordered-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-stream-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-stream" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_fs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_fs-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_fs" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_fs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_full-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_full" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_io_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_io_std-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_io_std" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_io_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_io_util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_io_util-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_io_util" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_io_util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_macros-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_macros" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_net-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_net-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_net" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_net-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_process-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_process-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_process" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_process-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_rt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_rt-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_rt" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_rt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_signal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_signal-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_signal" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_signal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_sync-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_sync-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_sync" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_sync-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_test_util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_test_util-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_test_util" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_test_util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio_time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_time-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio_time" feature of the "%{crate}" crate.

%files       -n %{name}+tokio_time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+web_stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+web_stream-devel %{_description}

This package contains library source intended for building other packages which
use the "web_stream" feature of the "%{crate}" crate.

%files       -n %{name}+web_stream-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm 0644 %{SOURCE1} LICENSE-MIT
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n -f napi8,async,serde-json

%build
%cargo_build -n -f napi8,async,serde-json

%install
%cargo_install -n -f napi8,async,serde-json

%if %{with check}
%check
%cargo_test -n -f napi8,async,serde-json
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 3.10.3-0.3
- Enable the package with exact-release source and license provenance.
- Build and test Kreuzberg's selected Fedora Linux feature surface.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 3.10.3-0.2
- Install the pinned upstream MIT license omitted from the published crate.
