# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate sevenz-rust2
%global source_sha256 29225600349ef74beda5a9fffb36ac660a24613c0bde9315d0c49be1d51e9c24

Name:           rust-sevenz-rust2_0.20
Version:        0.20.2
Release:        0.1%{?dist}
Summary:        Rust library for 7z archive compression and extraction

License:        Apache-2.0
URL:            https://crates.io/crates/sevenz-rust2
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          sevenz-rust2-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust library for 7z archive compression and extraction.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE.dependencies
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes256-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes256-devel %{_description}

This package contains library source intended for building other packages which
use the "aes256" feature of the "%{crate}" crate.

%files       -n %{name}+aes256-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes256_wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes256_wasm-devel %{_description}

This package contains library source intended for building other packages which
use the "aes256_wasm" feature of the "%{crate}" crate.

%files       -n %{name}+aes256_wasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+brotli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brotli-devel %{_description}

This package contains library source intended for building other packages which
use the "brotli" feature of the "%{crate}" crate.

%files       -n %{name}+brotli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bzip2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bzip2-devel %{_description}

This package contains library source intended for building other packages which
use the "bzip2" feature of the "%{crate}" crate.

%files       -n %{name}+bzip2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compress-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-devel %{_description}

This package contains library source intended for building other packages which
use the "compress" feature of the "%{crate}" crate.

%files       -n %{name}+compress-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+default_wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default_wasm-devel %{_description}

This package contains library source intended for building other packages which
use the "default_wasm" feature of the "%{crate}" crate.

%files       -n %{name}+default_wasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deflate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deflate-devel %{_description}

This package contains library source intended for building other packages which
use the "deflate" feature of the "%{crate}" crate.

%files       -n %{name}+deflate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lz4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lz4-devel %{_description}

This package contains library source intended for building other packages which
use the "lz4" feature of the "%{crate}" crate.

%files       -n %{name}+lz4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nt-time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nt-time-devel %{_description}

This package contains library source intended for building other packages which
use the "nt-time" feature of the "%{crate}" crate.

%files       -n %{name}+nt-time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ppmd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ppmd-devel %{_description}

This package contains library source intended for building other packages which
use the "ppmd" feature of the "%{crate}" crate.

%files       -n %{name}+ppmd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+util-devel %{_description}

This package contains library source intended for building other packages which
use the "util" feature of the "%{crate}" crate.

%files       -n %{name}+util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zstd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zstd-devel %{_description}

This package contains library source intended for building other packages which
use the "zstd" feature of the "%{crate}" crate.

%files       -n %{name}+zstd-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.20.2-0.1
- Package the published library crate without an empty binary package.
