# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate sevenz-rust2
%global source_sha256 29225600349ef74beda5a9fffb36ac660a24613c0bde9315d0c49be1d51e9c24

Name:           rust-sevenz-rust2_0.20
Version:        0.20.2
Release:        0.3%{?dist}
Summary:        Rust library for 7z archive compression and extraction

License:        Apache-2.0
URL:            https://crates.io/crates/sevenz-rust2
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: omit unsupported WASM, LZ4, and NT-time feature surfaces while
# preserving the complete native default feature set and available optional
# compression backends. Not submitted upstream because this is a distribution
# dependency selection.
Patch0:         sevenz-rust2-fix-metadata-auto.diff
# Fedora-specific: reuse the byte-identical packaged project license as the test
# payload so the crate-devel package does not ship a duplicate license fixture.
# Not submitted upstream because this is a distribution payload cleanup.
Patch1:         sevenz-rust2-reuse-license-fixture.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust library for 7z archive compression and extraction.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE.dependencies
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes256-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes256-devel %{_description}

This package contains library source intended for building other packages which
use the "aes256" feature of the "%{crate}" crate.

%files       -n %{name}+aes256-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+brotli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brotli-devel %{_description}

This package contains library source intended for building other packages which
use the "brotli" feature of the "%{crate}" crate.

%files       -n %{name}+brotli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bzip2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bzip2-devel %{_description}

This package contains library source intended for building other packages which
use the "bzip2" feature of the "%{crate}" crate.

%files       -n %{name}+bzip2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compress-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-devel %{_description}

This package contains library source intended for building other packages which
use the "compress" feature of the "%{crate}" crate.

%files       -n %{name}+compress-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deflate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deflate-devel %{_description}

This package contains library source intended for building other packages which
use the "deflate" feature of the "%{crate}" crate.

%files       -n %{name}+deflate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ppmd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ppmd-devel %{_description}

This package contains library source intended for building other packages which
use the "ppmd" feature of the "%{crate}" crate.

%files       -n %{name}+ppmd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+util-devel %{_description}

This package contains library source intended for building other packages which
use the "util" feature of the "%{crate}" crate.

%files       -n %{name}+util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zstd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zstd-devel %{_description}

This package contains library source intended for building other packages which
use the "zstd" feature of the "%{crate}" crate.

%files       -n %{name}+zstd-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%{__rm} -f tests/resources/apache2.txt
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.20.2-0.3
- Reuse the project license as the test fixture and omit its duplicate copy.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.20.2-0.2
- Enable configured SCM publication with the supported native feature surface.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.20.2-0.1
- Package the published library crate without an empty binary package.
