# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate phf_shared
%global source_sha256 c6fd9027e2d9319be6349febd1db4e8d02aa544921200c9b777720ac34a3aa89

Name:           rust-phf_shared0.14
Version:        0.14.0
Release:        0.2%{?dist}
Summary:        Support code shared by PHF libraries

License:        MIT
URL:            https://crates.io/crates/phf_shared
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Support code shared by PHF libraries.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ptrhash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ptrhash-devel %{_description}

This package contains library source intended for building other packages which
use the "ptrhash" feature of the "%{crate}" crate.

%files       -n %{name}+ptrhash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uncased-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uncased-devel %{_description}

This package contains library source intended for building other packages which
use the "uncased" feature of the "%{crate}" crate.

%files       -n %{name}+uncased-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicase-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicase-devel %{_description}

This package contains library source intended for building other packages which
use the "unicase" feature of the "%{crate}" crate.

%files       -n %{name}+unicase-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.2
- Enable the independently eligible leaf for six-cell SCM COPR publication.
- Use the immutable static crates.io archive for source generation.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.1
- Add the initial repository packaging changelog.
