# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate serde_toon_format
%global source_sha256 45abc88be1b465c1676fbbe94f866e872d3e9c22b3c10de6e1d90ae76dd45d51

Name:           rust-serde_toon_format0.1
Version:        0.1.2
Release:        0.1%{?dist}
Summary:        Serde-compatible TOON v3.0 encoder/decoder

License:        MIT
URL:            https://crates.io/crates/serde_toon_format
Source:         %{crates_source}
Patch:          serde_toon_format-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Serde-compatible TOON v3.0 encoder/decoder.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parallel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parallel-devel %{_description}

This package contains library source intended for building other packages which
use the "parallel" feature of the "%{crate}" crate.

%files       -n %{name}+parallel-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
chmod 0755 benchmarks/flamegraph_to_csv.py
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.1.2-0.1
- Preserve executable mode for the benchmark Python helper.
