# Adapted from Fedora commit 34ef88922dc4d3218fe3c9caebcb33282ccfaf5a.
# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate hayro-jpeg2000
%global source_sha256 c75ab947623ef4ccaa7acf0579edf7cbb5a73838e3839a7be73335e522f433a1

Name:           rust-hayro-jpeg2000
Version:        0.3.5
Release:        1.1%{?dist}
Summary:        Memory-safe, pure-Rust JPEG 2000 decoder

License:        (Apache-2.0 OR MIT) AND CC0-1.0
URL:            https://crates.io/crates/hayro-jpeg2000
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: account for the bundled CC0 assets and remove the unused
# indicatif development dependency. Retained from Fedora commit
# 34ef88922dc4d3218fe3c9caebcb33282ccfaf5a; not submitted upstream because it
# describes the distribution package's complete source payload and test graph.
Patch0:         hayro-jpeg2000-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A memory-safe, pure-Rust JPEG 2000 decoder.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/assets/LICENSE.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fearless_simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fearless_simd-devel %{_description}

This package contains library source intended for building other packages which
use the "fearless_simd" feature of the "%{crate}" crate.

%files       -n %{name}+fearless_simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+logging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+logging-devel %{_description}

This package contains library source intended for building other packages which
use the "logging" feature of the "%{crate}" crate.

%files       -n %{name}+logging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd-devel %{_description}

This package contains library source intended for building other packages which
use the "simd" feature of the "%{crate}" crate.

%files       -n %{name}+simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jul 23 2026 Marcin FM <marcin@lgic.pl> - 0.3.5-1.1
- Adapt Fedora's 0.3.5 package for Fedora 43 Kreuzberg builds.
