# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate piston-float
%global source_sha256 ad78bf43dcf80e8f950c92b84f938a0fc7590b7f6866fbcbeca781609c115590

Name:           rust-piston-float1
Version:        1.0.1
Release:        0.1%{?dist}
Summary:        Traits for generic floats in game development

License:        MIT
URL:            https://crates.io/crates/piston-float
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Traits for generic floats in game development.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 1.0.1-0.1
- Add the initial repository packaging changelog.
