# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate outlook-pst
%global source_sha256 299eace9d895cc31490927d7de779f8e8f3deb5fb6bd1e68eb192aa1da19bd47

Name:           rust-outlook-pst1
Version:        1.2.0
Release:        0.1%{?dist}
Summary:        Outlook PST Store Provider in Rust

License:        MIT
URL:            https://crates.io/crates/outlook-pst
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Outlook PST Store Provider in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 1.2.0-0.1
- Add the initial repository packaging changelog.
