# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate comrak
%global source_sha256 0d5910408554659ed848ff469e67ec83b30f179e72cec286cfdae64d1616f466

Name:           rust-comrak0.54
Version:        0.54.0
Release:        0.2%{?dist}
Summary:        100% CommonMark-compatible GitHub Flavored Markdown parser

License:        BSD-2-Clause
URL:            https://crates.io/crates/comrak
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora packaging: remove benchmark-only and non-native target dependencies
# that are unavailable or unused in Fedora's native packaged-crate test graph.
# Upstream status: not submitted because upstream intentionally retains its
# benchmark and WASM/iOS target support.
Patch:          comrak-fix-metadata-auto.diff
# Fedora compatibility: retain the CLI feature while omitting the unavailable
# Fedora 43 bon 3 dependency and its generated builder APIs. The build script
# registers dormant bon cfg guards as an expected disabled value.
# The maintainer has accepted this reduced default interface temporarily.
# Upstream status: not submitted because upstream intentionally supports bon;
# this is a Fedora 43 dependency-availability choice.
Patch1:         comrak-f43-no-bon.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A 100% CommonMark-compatible GitHub Flavored Markdown parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/RELEASE_CHECKLIST.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+attributes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+attributes-devel %{_description}

This package contains library source intended for building other packages which
use the "attributes" feature of the "%{crate}" crate.

%files       -n %{name}+attributes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages which
use the "clap" feature of the "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cli-devel %{_description}

This package contains library source intended for building other packages which
use the "cli" feature of the "%{crate}" crate.

%files       -n %{name}+cli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+emojis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+emojis-devel %{_description}

This package contains library source intended for building other packages which
use the "emojis" feature of the "%{crate}" crate.

%files       -n %{name}+emojis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fmt2io-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fmt2io-devel %{_description}

This package contains library source intended for building other packages which
use the "fmt2io" feature of the "%{crate}" crate.

%files       -n %{name}+fmt2io-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+phoenix_heex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+phoenix_heex-devel %{_description}

This package contains library source intended for building other packages which
use the "phoenix_heex" feature of the "%{crate}" crate.

%files       -n %{name}+phoenix_heex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+shell-words-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+shell-words-devel %{_description}

This package contains library source intended for building other packages which
use the "shell-words" feature of the "%{crate}" crate.

%files       -n %{name}+shell-words-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+shortcodes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+shortcodes-devel %{_description}

This package contains library source intended for building other packages which
use the "shortcodes" feature of the "%{crate}" crate.

%files       -n %{name}+shortcodes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syntect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syntect-devel %{_description}

This package contains library source intended for building other packages which
use the "syntect" feature of the "%{crate}" crate.

%files       -n %{name}+syntect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syntect-fancy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syntect-fancy-devel %{_description}

This package contains library source intended for building other packages which
use the "syntect-fancy" feature of the "%{crate}" crate.

%files       -n %{name}+syntect-fancy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syntect-onig-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syntect-onig-devel %{_description}

This package contains library source intended for building other packages which
use the "syntect-onig" feature of the "%{crate}" crate.

%files       -n %{name}+syntect-onig-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 0.54.0-0.2
- Enable the accepted Fedora no-bon compatibility interface.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.54.0-0.1
- Add the initial repository packaging changelog.
