# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate hashify
%global source_sha256 dd1246c0e5493286aeb2dde35b1f4eb9c4ce00e628641210a5e553fc001a1f26

Name:           rust-hashify0.2
Version:        0.2.9
Release:        0.2%{?dist}
Summary:        Fast perfect hashing without dependencies

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/hashify
Source0:        %{crates_source}
# Fedora does not need the benchmark-only Criterion dependency.
# Downstream-only registry integration metadata; not submitted upstream.
Patch0:         hashify-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fast perfect hashing without dependencies.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSES/Apache-2.0.txt
%license %{crate_instdir}/LICENSES/MIT.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+force-32bit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+force-32bit-devel %{_description}

This package contains library source intended for building other packages which
use the "force-32bit" feature of the "%{crate}" crate.

%files       -n %{name}+force-32bit-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.9-0.2
- Enable configured SCM publication from the immutable crates.io source.
- Mark both included project license texts as license files.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.2.9-0.1
- Add the initial repository packaging changelog.
