# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate wide
%global source_sha256 dfdfe6a32973f2d1b268b8895845a8a96cac2f0191e72c27cc929036060dbf89

Name:           rust-wide1
Version:        1.5.0
Release:        0.3%{?dist}
Summary:        To help you go wide

License:        Zlib OR Apache-2.0 OR MIT
URL:            https://crates.io/crates/wide
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: limit this compatibility package to the stable default/std
# surface needed by simba and omit unselected serde and benchmark dependencies.
# Not submitted upstream because this is a distribution feature selection.
Patch0:         wide-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A crate to help you go wide.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-ZLIB.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/changelog.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n -f std

%build
%cargo_build -n -f std

%install
%cargo_install -n -f std

%if %{with check}
%check
%cargo_test -n -f std
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 1.5.0-0.3
- Enable configured SCM publication from the immutable crates.io source.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 1.5.0-0.2
- Initial Fedora 44 compatibility package
