# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate phf_macros
%global source_sha256 5fa8d0ca26d424d27630da600c6624696e7dec8bf7b3b492b383c5dc49e5e085

Name:           rust-phf_macros0.14
Version:        0.14.0
Release:        0.2%{?dist}
Summary:        Macros to generate types in the phf crate

License:        MIT
URL:            https://crates.io/crates/phf_macros
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Macros to generate types in the phf crate.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ptrhash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ptrhash-devel %{_description}

This package contains library source intended for building other packages which
use the "ptrhash" feature of the "%{crate}" crate.

%files       -n %{name}+ptrhash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uncased-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uncased-devel %{_description}

This package contains library source intended for building other packages which
use the "uncased" feature of the "%{crate}" crate.

%files       -n %{name}+uncased-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uncased_-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uncased_-devel %{_description}

This package contains library source intended for building other packages which
use the "uncased_" feature of the "%{crate}" crate.

%files       -n %{name}+uncased_-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicase-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicase-devel %{_description}

This package contains library source intended for building other packages which
use the "unicase" feature of the "%{crate}" crate.

%files       -n %{name}+unicase-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicase_-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicase_-devel %{_description}

This package contains library source intended for building other packages which
use the "unicase_" feature of the "%{crate}" crate.

%files       -n %{name}+unicase_-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.2
- Enable the independently eligible leaf for six-cell SCM COPR publication.
- Use the immutable static crates.io archive for source generation.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.1
- Add the initial repository packaging changelog.
