# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate infer
%global source_sha256 a588916bfdfd92e71cacef98a63d9b1f0d74d6599980d11894290e7ddefffcf7

Name:           rust-infer0.19
Version:        0.19.0
Release:        0.1%{?dist}
Summary:        Small crate to infer file type based on magic number signatures

License:        MIT
URL:            https://crates.io/crates/infer
Source:         %{crates_source}
Patch:          infer-fedora-doctests.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Small crate to infer file type based on magic number signatures.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cfb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cfb-devel %{_description}

This package contains library source intended for building other packages which
use the "cfb" feature of the "%{crate}" crate.

%files       -n %{name}+cfb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.19.0-0.1
- Add the initial repository packaging changelog.
