# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate napi-derive
%global source_sha256 d4ba572deef53e2c386759a8c2014175a62679d74ff83adc205c8bc0e0285727

Name:           rust-napi-derive3
Version:        3.5.9
Release:        0.1%{?dist}
Summary:        N-API procedural macros

License:        MIT
URL:            https://crates.io/crates/napi-derive
Source:         %{crates_source}
Patch:          napi-derive-fedora-crates.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
N-API procedural macros.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compat-mode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compat-mode-devel %{_description}

This package contains library source intended for building other packages which
use the "compat-mode" feature of the "%{crate}" crate.

%files       -n %{name}+compat-mode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ctor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ctor-devel %{_description}

This package contains library source intended for building other packages which
use the "ctor" feature of the "%{crate}" crate.

%files       -n %{name}+ctor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+noop-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+noop-devel %{_description}

This package contains library source intended for building other packages which
use the "noop" feature of the "%{crate}" crate.

%files       -n %{name}+noop-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+strict-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strict-devel %{_description}

This package contains library source intended for building other packages which
use the "strict" feature of the "%{crate}" crate.

%files       -n %{name}+strict-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+type-def-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+type-def-devel %{_description}

This package contains library source intended for building other packages which
use the "type-def" feature of the "%{crate}" crate.

%files       -n %{name}+type-def-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 3.5.9-0.1
- Add the initial repository packaging changelog.
