# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate bufrw
%global source_sha256 394c22b416e3981206df472c3bcbbf9ae130883619aefc2199e6087517af1bba

Name:           rust-bufrw0.2
Version:        0.2.0
Release:        0.2%{?dist}
Summary:        Single adapter that buffers reads and writes on the same stream

License:        MIT
URL:            https://crates.io/crates/bufrw
Source:         %{crates_source}
# Omit the benchmark-only Criterion dependency from Fedora's library build graph.
# Fedora-specific; not submitted because upstream intentionally retains the benchmark.
Patch:          bufrw-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
This crate provides a single adapter that buffers reads and writes on
the same stream.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/License
%doc %{crate_instdir}/Changelog.md
%doc %{crate_instdir}/Readme.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.2
- Document the benchmark-only dependency pruning patch.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.2.0-0.1
- Add the initial repository packaging changelog.
