# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate hayro-ccitt
%global source_sha256 9f4d0e94ddd48749f06bbe4e5389fb9799a0c45bcaf00495042076ef05e3241a

Name:           rust-hayro-ccitt0.3
Version:        0.3.0
Release:        0.1%{?dist}
Summary:        Decoder for group 3 and group 4 CCITT images

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/hayro-ccitt
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A decoder for group 3 and group 4 CCITT images.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 0.3.0-0.1
- Add the initial repository packaging changelog.
