# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate oem_cp
%global source_sha256 a95602f5a6eec5b15394516448c0b6fc2f2ef4ca2a9ab2951a91a18cec516bf0

Name:           rust-oem_cp1
Version:        1.3.0
Release:        0.2%{?dist}
Summary:        Rust library that handles OEM code pages

License:        MIT
URL:            https://crates.io/crates/oem_cp
Source:         %{crates_source}
# Fedora packaging: remove Windows-only development dependencies from Fedora's
# non-Windows crate graph.
# Upstream status: not submitted because upstream supports Windows tests, while
# this package targets Fedora.
Patch:          oem_cp-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust library that handles OEM code pages (e.g. CP{437,737,850}) for
single byte character sets.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 1.3.0-0.2
- Document the foreign-target patch purpose and upstream status.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 1.3.0-0.1
- Add the initial repository packaging changelog.
