# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate finl_unicode
%global source_sha256 9844ddc3a6e533d62bba727eb6c28b5d360921d5175e9ff0f1e621a5c590a4d5

Name:           rust-finl_unicode1
Version:        1.4.0
Release:        0.1%{?dist}
Summary:        Library for handling Unicode functionality for finl

License:        (MIT OR Apache-2.0) AND Unicode-DFS-2016
URL:            https://crates.io/crates/finl_unicode
Source:         %{crates_source}
Patch:          finl_unicode-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for handling Unicode functionality for finl, including categories and
character-cluster segmentation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/LICENSE-UNICODE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+categories-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+categories-devel %{_description}

This package contains library source intended for building other packages which
use the "categories" feature of the "%{crate}" crate.

%files       -n %{name}+categories-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+grapheme_clusters-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grapheme_clusters-devel %{_description}

This package contains library source intended for building other packages which
use the "grapheme_clusters" feature of the "%{crate}" crate.

%files       -n %{name}+grapheme_clusters-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 1.4.0-0.1
- Add the initial changelog and clarify Unicode segmentation wording.
