# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate caseless
%global source_sha256 8b6fd507454086c8edfd769ca6ada439193cdb209c7681712ef6275cccbfe5d8

Name:           rust-caseless0.2
Version:        0.2.2
Release:        0.1%{?dist}
Summary:        Unicode caseless matching

License:        MIT
URL:            https://crates.io/crates/caseless
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Unicode caseless matching.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CaseFolding.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 0.2.2-0.1
- Add the initial repository packaging changelog.
