# Adapted from Fedora commit 3309ae290a9d488a729276d467b1b20f89093572.
# Generated by rust2rpm 28
# Nearly all tests require omitted tests/data inputs, including precompiled
# executables with unresolved provenance and licensing.
%bcond check 0
%global debug_package %{nil}

%global crate lzma-rust2
%global source_sha256 ca93e534d1142d1d0dcca6d25fe302508a5dfb40b302802904577725ea0b695b

Name:           rust-lzma-rust2_0.16
Version:        0.16.5
Release:        2.1%{?dist}
Summary:        Pure Rust compression library

License:        Apache-2.0
URL:            https://crates.io/crates/lzma-rust2
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: remove benchmark-only criterion and the unpackaged liblzma
# development dependency. Retained from Fedora commit
# 3309ae290a9d488a729276d467b1b20f89093572; not submitted upstream because the
# patch selects the distribution test graph without changing library behavior.
Patch0:         lzma-rust2-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure Rust compression library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoder-devel %{_description}

This package contains library source intended for building other packages which
use the "encoder" feature of the "%{crate}" crate.

%files       -n %{name}+encoder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lzip-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lzip-devel %{_description}

This package contains library source intended for building other packages which
use the "lzip" feature of the "%{crate}" crate.

%files       -n %{name}+lzip-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+optimization-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+optimization-devel %{_description}

This package contains library source intended for building other packages which
use the "optimization" feature of the "%{crate}" crate.

%files       -n %{name}+optimization-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sha2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sha2-devel %{_description}

This package contains library source intended for building other packages which
use the "sha2" feature of the "%{crate}" crate.

%files       -n %{name}+sha2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xz-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xz-devel %{_description}

This package contains library source intended for building other packages which
use the "xz" feature of the "%{crate}" crate.

%files       -n %{name}+xz-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jul 23 2026 Marcin FM <marcin@lgic.pl> - 0.16.5-2.1
- Retain Fedora's 0.16 branch for Rawhide sevenz-rust2 consumers.
