# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate phf_generator
%global source_sha256 aeb62e0959d5a1bebc965f4d15d9e2b7cea002b6b0f5ba8cde6cc26738467100

Name:           rust-phf_generator0.14
Version:        0.14.0
Release:        0.3%{?dist}
Summary:        PHF generation logic

License:        MIT
URL:            https://crates.io/crates/phf_generator
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora packaging: omit the benchmark target and its Criterion-only
# development dependency from the packaged crate graph.
# Upstream status: not submitted because upstream intentionally retains the
# benchmark, while Fedora does not package benchmark-only inputs.
Patch:          phf_generator-0.14.0-no-benchmarks.patch

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
PHF generation logic.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ptrhash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ptrhash-devel %{_description}

This package contains library source intended for building other packages which
use the "ptrhash" feature of the "%{crate}" crate.

%files       -n %{name}+ptrhash-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.3
- Enable the independently eligible leaf for six-cell SCM COPR publication.
- Use the immutable static crates.io archive for source generation.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.2
- Document the benchmark-pruning patch purpose and upstream status.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.1
- Add the initial repository packaging changelog.
