# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate jetscii
%global source_sha256 47f142fe24a9c9944451e8349de0a56af5f3e7226dc46f3ed4d4ecc0b85af75e

Name:           rust-jetscii0.5
Version:        0.5.3
Release:        0.2%{?dist}
Summary:        Search strings and byte slices for ASCII values

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/jetscii
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora carries the maintained memmap2 replacement for the unmaintained memmap.
# Downstream-only registry integration metadata; not submitted upstream.
Patch0:         jetscii-fix-metadata.diff
# Stable Fedora Rust cannot build these unselected nightly-only interfaces.
# Downstream-only feature pruning; not submitted upstream.
Patch1:         jetscii-drop-nightly-features.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A tiny library to efficiently search strings and byte slices for sets of
ASCII characters or bytes.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.5.3-0.2
- Enable configured SCM publication from the immutable crates.io source.
- Remove unselected nightly-only feature interfaces.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.5.3-0.1
- Shorten the package summary for RPM metadata.
