# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate napi-build
%global source_sha256 c9c366d2c8c60b86fa632df75f745509b52f9128f91a6bad4c796e44abb505e1
%global license_commit e9c50bb430b7d34659c0541f600e1e323d37432a
%global license_sha256 3f1ce66533302df3a32edbfdfc0b78f0dd34659e4c1f5817162e5ea3c2297215

Name:           rust-napi-build2
Version:        2.3.2
Release:        0.3%{?dist}
Summary:        N-API build support

License:        MIT
URL:            https://crates.io/crates/napi-build
# crates.io's API download route returns HTTP 403 in COPR source builders.
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# The registry archive omits the workspace license; pin the release commit.
Source1:        https://raw.githubusercontent.com/napi-rs/napi-rs/%{license_commit}/LICENSE#/%{crate}-%{version}-LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
N-API build support.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm 0644 %{SOURCE1} LICENSE
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 2.3.2-0.3
- Use the direct static registry archive accepted by COPR source builders.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 2.3.2-0.2
- Enable configured SCM publication with the immutable upstream license text.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 2.3.2-0.1
- Add the initial repository packaging changelog.
