# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate geo-types
%global source_sha256 94776032c45f950d30a13af6113c2ad5625316c9abfbccee4dd5a6695f8fe0f5
%global license_commit 981be9feea12cdede572fb252064536cb8b287b1
%global license_mit_sha256 2f8267b247fd81e9555a2e196e119a5b341bcae21011cd93985c312f1312f727
%global license_apache_sha256 a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2

Name:           rust-geo-types0.7
Version:        0.7.19
Release:        0.2%{?dist}
Summary:        Geographic primitive data types

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/geo-types
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# The crate archive omits the workspace-root license texts; pin the release commit.
Source1:        https://raw.githubusercontent.com/georust/geo/%{license_commit}/LICENSE-MIT#/geo-types-LICENSE-MIT
Source2:        https://raw.githubusercontent.com/georust/geo/%{license_commit}/LICENSE-APACHE#/geo-types-LICENSE-APACHE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Geographic primitive data types.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGES.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__allow_deprecated_features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__allow_deprecated_features-devel %{_description}

This package contains library source intended for building other packages which
use the "__allow_deprecated_features" feature of the "%{crate}" crate.

%files       -n %{name}+__allow_deprecated_features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+approx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+approx-devel %{_description}

This package contains library source intended for building other packages which
use the "approx" feature of the "%{crate}" crate.

%files       -n %{name}+approx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multithreading-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multithreading-devel %{_description}

This package contains library source intended for building other packages which
use the "multithreading" feature of the "%{crate}" crate.

%files       -n %{name}+multithreading-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar" feature of the "%{crate}" crate.

%files       -n %{name}+rstar-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar_0_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar_0_10-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar_0_10" feature of the "%{crate}" crate.

%files       -n %{name}+rstar_0_10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar_0_11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar_0_11-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar_0_11" feature of the "%{crate}" crate.

%files       -n %{name}+rstar_0_11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar_0_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar_0_12-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar_0_12" feature of the "%{crate}" crate.

%files       -n %{name}+rstar_0_12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar_0_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar_0_8-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar_0_8" feature of the "%{crate}" crate.

%files       -n %{name}+rstar_0_8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rstar_0_9-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rstar_0_9-devel %{_description}

This package contains library source intended for building other packages which
use the "rstar_0_9" feature of the "%{crate}" crate.

%files       -n %{name}+rstar_0_9-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+spade_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spade_2-devel %{_description}

This package contains library source intended for building other packages which
use the "spade_2" feature of the "%{crate}" crate.

%files       -n %{name}+spade_2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar_0_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar_0_10-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar_0_10" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar_0_10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar_0_11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar_0_11-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar_0_11" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar_0_11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar_0_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar_0_12-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar_0_12" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar_0_12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar_0_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar_0_8-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar_0_8" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar_0_8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-rstar_0_9-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-rstar_0_9-devel %{_description}

This package contains library source intended for building other packages which
use the "use-rstar_0_9" feature of the "%{crate}" crate.

%files       -n %{name}+use-rstar_0_9-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_mit_sha256}  %{SOURCE1}" | sha256sum -c -
echo "%{license_apache_sha256}  %{SOURCE2}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm0644 %{SOURCE1} LICENSE-MIT
install -pm0644 %{SOURCE2} LICENSE-APACHE
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 0.7.19-0.2
- Enable stable-release publication with exact upstream license texts.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.7.19-0.1
- Add the initial changelog and clarify geographic type wording.
