# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate convert_case
%global source_sha256 affbf0190ed2caf063e3def54ff444b449371d55c58e513a95ab98eca50adb49

Name:           rust-convert_case0.11
Version:        0.11.0
Release:        0.1%{?dist}
Summary:        Convert strings into any case

License:        MIT
URL:            https://crates.io/crates/convert_case
Source:         %{crates_source}
Patch:          convert_case-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Convert strings into any case.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.11.0-0.1
- Add the initial repository packaging changelog.
