# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate imageproc
%global source_sha256 c7b27bc0867dc40df08deb53d6e96342db6e0702e7ae33ed09a4eba33e594b05

Name:           rust-imageproc0.27
Version:        0.27.0
Release:        0.1%{?dist}
Summary:        Image processing operations

License:        MIT
URL:            https://crates.io/crates/imageproc
Source:         %{crates_source}
# Tests require the upstream fixture omitted from the crates.io archive.
Source1:        imageproc-0.27.0-DejaVuSans.ttf
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          imageproc-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Image processing operations.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+display-window-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+display-window-devel %{_description}

This package contains library source intended for building other packages which
use the "display-window" feature of the "%{crate}" crate.

%files       -n %{name}+display-window-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fft-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fft-devel %{_description}

This package contains library source intended for building other packages which
use the "fft" feature of the "%{crate}" crate.

%files       -n %{name}+fft-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+katexit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+katexit-devel %{_description}

This package contains library source intended for building other packages which
use the "katexit" feature of the "%{crate}" crate.

%files       -n %{name}+katexit-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sdl2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sdl2-devel %{_description}

This package contains library source intended for building other packages which
use the "sdl2" feature of the "%{crate}" crate.

%files       -n %{name}+sdl2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+text-devel %{_description}

This package contains library source intended for building other packages which
use the "text" feature of the "%{crate}" crate.

%files       -n %{name}+text-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -Dpm 0644 %{SOURCE1} tests/data/fonts/DejaVuSans.ttf
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jul 16 2026 OpenCode <noreply@example.invalid> - 0.27.0-0.1
- Restore the upstream DejaVuSans test fixture omitted from the crates.io archive.
