# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate cfb
%global source_sha256 a347dcabdae9c31b0825fd6a8bed285ec9c2acb89c47827126d52fa4f59cece3

Name:           rust-cfb0.14
Version:        0.14.0
Release:        0.3%{?dist}
Summary:        Read/write Compound File Binary (structured storage) files

License:        MIT
URL:            https://crates.io/crates/cfb
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: omit benchmark-only Criterion 0.8, which upstream retains:
# https://github.com/mdsteele/rust-cfb/commit/0c4cc5be137dc2d0aef70889721f34217903d9fc
# Run the debug-assertion-dependent should-panic test only with debug assertions;
# upstream still leaves it unguarded after its introduction:
# https://github.com/mdsteele/rust-cfb/commit/4bdfbdf162ca871ef412d68b55d10b417b90df48
Patch:          cfb-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Read/write Compound File Binary (structured storage) files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 25 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.3
- Document the Fedora patch purpose and upstream status.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.2
- Enable configured SCM publication from the immutable crates.io source.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.14.0-0.1
- Add the initial repository packaging changelog.
