# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate vecmath
%global source_sha256 956ae1e0d85bca567dee1dcf87fb1ca2e792792f66f87dced8381f99cd91156a

Name:           rust-vecmath1
Version:        1.0.0
Release:        0.1%{?dist}
Summary:        Simple and type agnostic library for vector math designed for reexporting

License:        MIT
URL:            https://crates.io/crates/vecmath
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple and type agnostic library for vector math designed for
reexporting.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 1.0.0-0.1
- Add the initial repository packaging changelog.
