# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate biblib
%global source_sha256 17cf00fd6ddffdc0606a4eca2f55e09385ae61437a5e53dccdab6060db544968

Name:           rust-biblib0.7
Version:        0.7.2
Release:        0.1%{?dist}
Summary:        Parse, manage, and deduplicate academic citations

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/biblib
Source:         %{crates_source}
Patch:          biblib-rstest-0.26.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Parse, manage, and deduplicate academic citations.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bib-devel %{_description}

This package contains library source intended for building other packages which
use the "bib" feature of the "%{crate}" crate.

%files       -n %{name}+bib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+csv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+csv-devel %{_description}

This package contains library source intended for building other packages which
use the "csv" feature of the "%{crate}" crate.

%files       -n %{name}+csv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dedupe-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dedupe-devel %{_description}

This package contains library source intended for building other packages which
use the "dedupe" feature of the "%{crate}" crate.

%files       -n %{name}+dedupe-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+diagnostics-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+diagnostics-devel %{_description}

This package contains library source intended for building other packages which
use the "diagnostics" feature of the "%{crate}" crate.

%files       -n %{name}+diagnostics-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+enw-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+enw-devel %{_description}

This package contains library source intended for building other packages which
use the "enw" feature of the "%{crate}" crate.

%files       -n %{name}+enw-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pubmed-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pubmed-devel %{_description}

This package contains library source intended for building other packages which
use the "pubmed" feature of the "%{crate}" crate.

%files       -n %{name}+pubmed-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ris-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ris-devel %{_description}

This package contains library source intended for building other packages which
use the "ris" feature of the "%{crate}" crate.

%files       -n %{name}+ris-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xml-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xml-devel %{_description}

This package contains library source intended for building other packages which
use the "xml" feature of the "%{crate}" crate.

%files       -n %{name}+xml-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.7.2-0.1
- Add the initial repository packaging changelog.
