# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate fmt2io
%global source_sha256 6b6129284da9f7e5296cc22183a63f24300e945e297705dcc0672f7df01d62c8

Name:           rust-fmt2io1
Version:        1.0.0
Release:        0.1%{?dist}
Summary:        Bridge between std::io::Write and std::fmt::Write

License:        MITNFA
URL:            https://crates.io/crates/fmt2io
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A bridge between std::io::Write and std::fmt::Write.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 1.0.0-0.1
- Add the initial repository packaging changelog.
