# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate roman-numerals-rs
%global source_sha256 c85cd47a33a4510b1424fe796498e174c6a9cf94e606460ef022a19f3e4ff85e

Name:           rust-roman-numerals-rs3
Version:        3.1.0
Release:        0.1%{?dist}
Summary:        Manipulate well-formed Roman numerals

License:        0BSD OR CC0-1.0
URL:            https://crates.io/crates/roman-numerals-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Manipulate well-formed Roman numerals.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 3.1.0-0.1
- Add the initial repository packaging changelog.
