name: rust-tree-sitter-rust0.24
status: enabled
blockers: []
upstream:
  provider: crates_io
  crate: tree-sitter-rust
  version_requirement: = 0.24.2
  current_version: 0.24.2
  source_url_template: https://static.crates.io/crates/tree-sitter-rust/tree-sitter-rust-{version}.crate
  source_sha256: 439e577dbe07423ec2582ac62c7531120dbfccfa6e5f92406f93dd271a120e45
copr:
  enabled: true
  subdir: packages/rust-tree-sitter-rust0.24
  spec: rust-tree-sitter-rust0.24.spec
