# Generated by rust2rpm 29
%bcond check 1
%global debug_package %{nil}

%global crate fearless_simd
%global source_sha256 011821dd96916694f4133efae9198c02636d185af2ecb51d73ef90cc95429fa2

Name:           rust-fearless_simd
Version:        0.4.1
Release:        1.1%{?dist}
Summary:        Unified interface for portable SIMD vector types

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/fearless_simd
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora 44 commit ae60d4a5155027e05cc9125dc47fc609e31e5917: normalize
# incomplete license metadata and remove unpackaged or unused dev dependencies.
Patch:          fearless_simd-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Unified interface for portable SIMD vector types.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+aarch64_neon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aarch64_neon-devel %{_description}

This package contains library source intended for building other packages which
use the "aarch64_neon" feature of the "%{crate}" crate.

%files       -n %{name}+aarch64_neon-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+avx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+avx-devel %{_description}

This package contains library source intended for building other packages which
use the "avx" feature of the "%{crate}" crate.

%files       -n %{name}+avx-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+avx2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+avx2-devel %{_description}

This package contains library source intended for building other packages which
use the "avx2" feature of the "%{crate}" crate.

%files       -n %{name}+avx2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+vmx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vmx-devel %{_description}

This package contains library source intended for building other packages which
use the "vmx" feature of the "%{crate}" crate.

%files       -n %{name}+vmx-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+wasm_simd128-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm_simd128-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm_simd128" feature of the "%{crate}" crate.

%files       -n %{name}+wasm_simd128-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+x86_v3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+x86_v3-devel %{_description}

This package contains library source intended for building other packages which
use the "x86_v3" feature of the "%{crate}" crate.

%files       -n %{name}+x86_v3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jul 23 2026 Marcin FM <marcin@lgic.pl> - 0.4.1-1.1
- Add the Fedora 44 package for the Fedora 43 Hayro dependency.

* Tue May 06 2025 Fabio Valentini <decathorpe@gmail.com> - 0.4.1-1
- Update to version 0.4.1; Fixes RHBZ#2341909
