# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate napi-derive-backend
%global source_sha256 ddd961eb2aa8965e3f29722d754f3a86907eb1984e2fbcbe3fe87b9a02d6bfba
%global license_commit dea608eae7481a47d64aab563a2ab5cdd8eda03c
%global license_sha256 3f1ce66533302df3a32edbfdfc0b78f0dd34659e4c1f5817162e5ea3c2297215

Name:           rust-napi-derive-backend5
Version:        5.1.1
Release:        0.3%{?dist}
Summary:        Code generation backend for napi procedural macro

License:        MIT
URL:            https://crates.io/crates/napi-derive-backend
Source:         %{crates_source}
Source1:        https://raw.githubusercontent.com/napi-rs/napi-rs/%{license_commit}/LICENSE#/napi-rs-LICENSE
Patch2:         napi-derive-backend-private-semver.diff
Patch3:         napi-derive-backend-ctor-syntax.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Code generation backend for the napi procedural macro.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+strict-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strict-devel %{_description}

This package contains library source intended for building other packages which
use the "strict" feature of the "%{crate}" crate.

%files       -n %{name}+strict-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+type-def-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+type-def-devel %{_description}

This package contains library source intended for building other packages which
use the "type-def" feature of the "%{crate}" crate.

%files       -n %{name}+type-def-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm 0644 %{SOURCE1} LICENSE-MIT
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f strict,type-def

%build
%cargo_build -f strict,type-def

%install
%cargo_install -f strict,type-def

%if %{with check}
%check
%cargo_test -f strict,type-def
%endif

%changelog
* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 5.1.1-0.3
- Restore the retained ctor 0.6 compatibility patch.
- Install the pinned upstream MIT license omitted from the published crate.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 5.1.1-0.2
- Generate ctor 0.6-compatible N-API registration functions.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 5.1.1-0.1
- Initial package
