# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate whatlang
%global source_sha256 f5e8f38b596e2a359b755342473520a99421e43658548c79489ee221b728c107
%global license_commit 584009bbdbd715681fc1c144ac986814104bedbc
%global license_sha256 9fb62b415784b27e358a03677cac6b56de73425f4fdbb5f4ecf19650af5dfe0c

Name:           rust-whatlang0.18
Version:        0.18.0
Release:        0.2%{?dist}
Summary:        Fast and lightweight language identification library for Rust

License:        MIT
URL:            https://crates.io/crates/whatlang
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# The crate include list omits the project license text; pin the publishing commit.
Source1:        https://raw.githubusercontent.com/greyblake/whatlang-rs/%{license_commit}/LICENSE#/whatlang-LICENSE
# Fedora-specific: remove the unavailable arbtest 0.2 development dependency.
# Not submitted upstream because upstream intentionally retains that test surface.
Patch0:         whatlang-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fast and lightweight language identification library for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dev-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dev-devel %{_description}

This package contains library source intended for building other packages which
use the "dev" feature of the "%{crate}" crate.

%files       -n %{name}+dev-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+enum-map-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+enum-map-devel %{_description}

This package contains library source intended for building other packages which
use the "enum-map" feature of the "%{crate}" crate.

%files       -n %{name}+enum-map-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm0644 %{SOURCE1} LICENSE
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 0.18.0-0.2
- Enable configured SCM publication with the exact upstream MIT text.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.18.0-0.1
- Add the initial repository packaging changelog.
