# Generated by rust2rpm 28; provisional system ONNX Runtime validation package.
%bcond check 1
%global debug_package %{nil}

%global crate ort-sys
%global source_sha256 d7b497d21a8b6fbb4b5a544f8fadb77e801a09ae0add9e411d31c6f89e3c1e90
%global crate_version 2.0.0-rc.12

Name:           rust-ort-sys
Version:        2.0.0~rc.12
Release:        0.1%{?dist}
Summary:        Unsafe Rust bindings for ONNX Runtime

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/ort-sys
Source:         %{crates_source %{crate} %{crate_version}}
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(libonnxruntime) >= 1.18

%global _description %{expand:
Unsafe Rust bindings for ONNX Runtime.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+api-17-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+api-17-devel %{_description}

This package contains library source for the api-17 feature of %{crate}.

%files       -n %{name}+api-17-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+api-18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+api-18-devel %{_description}

This package contains library source for the api-18 feature of %{crate}.

%files       -n %{name}+api-18-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disable-linking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disable-linking-devel %{_description}

This package contains library source for the disable-linking feature of %{crate}.

%files       -n %{name}+disable-linking-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source for the std feature of %{crate}.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{crate_version}
%cargo_prep

%generate_buildrequires
export CARGO_NET_OFFLINE=true
export ORT_OFFLINE=1
export ORT_SKIP_DOWNLOAD=1
export ORT_LIB_PATH=%{_libdir}
export ORT_PREFER_DYNAMIC_LINK=1
%cargo_generate_buildrequires -n -f api-18,std

%build
export CARGO_NET_OFFLINE=true
export ORT_OFFLINE=1
export ORT_SKIP_DOWNLOAD=1
export ORT_LIB_PATH=%{_libdir}
export ORT_PREFER_DYNAMIC_LINK=1
%cargo_build -n -f api-18,std

%install
export CARGO_NET_OFFLINE=true
export ORT_OFFLINE=1
export ORT_SKIP_DOWNLOAD=1
export ORT_LIB_PATH=%{_libdir}
export ORT_PREFER_DYNAMIC_LINK=1
%cargo_install -n -f api-18,std

%if %{with check}
%check
export CARGO_NET_OFFLINE=true
export ORT_OFFLINE=1
export ORT_SKIP_DOWNLOAD=1
export ORT_LIB_PATH=%{_libdir}
export ORT_PREFER_DYNAMIC_LINK=1
%cargo_test -n -f api-18,std
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 2.0.0~rc.12-0.1
- Add the initial repository packaging changelog.
%autochangelog
