# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate nalgebra
%global source_sha256 adc43a60c217b0c6ff46e47f26911015ad8d2e5a8be1af668c67e370d99a4346

Name:           rust-nalgebra0.35
Version:        0.35.0
Release:        0.3%{?dist}
Summary:        General-purpose linear algebra library

License:        Apache-2.0
URL:            https://crates.io/crates/nalgebra
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: limit this compatibility package to the base/default/std
# surface requested by imageproc. Remove optional conversion, macro, random,
# serialization, and glam branches. Not submitted upstream because this is a
# distribution feature selection.
Patch0:         nalgebra-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
General-purpose linear algebra library with transformations and
statically-sized or dynamically-sized matrices.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n -f std

%build
%cargo_build -n -f std

%install
%cargo_install -n -f std

%if %{with check}
%check
# * Run the library unit tests for the selected std surface. The published
#   integration target is excluded because it requires the deliberately omitted
#   debug, compare, rand, and macros features and their development
#   dependencies.
%cargo_test -n -f std -- --lib
%cargo_test -n -f std -- --examples
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.35.0-0.3
- Enable configured SCM publication for the selected default and std features.

* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 0.35.0-0.2
- Initial Fedora 44 compatibility package
