# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate jotdown
%global source_sha256 206bf4773a58f2a051a24fb77cb6c5eeaa84403c0dc5d072ec460ed1648db594

Name:           rust-jotdown0.10
Version:        0.10.0
Release:        0.1%{?dist}
Summary:        Parser for the Djot markup language

License:        MIT
URL:            https://crates.io/crates/jotdown
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A parser for the Djot markup language.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cli-devel %{_description}

This package contains library source intended for building other packages which
use the "cli" feature of the "%{crate}" crate.

%files       -n %{name}+cli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deterministic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deterministic-devel %{_description}

This package contains library source intended for building other packages which
use the "deterministic" feature of the "%{crate}" crate.

%files       -n %{name}+deterministic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+html-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+html-devel %{_description}

This package contains library source intended for building other packages which
use the "html" feature of the "%{crate}" crate.

%files       -n %{name}+html-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 17 2026 OpenCode <noreply@example.invalid> - 0.10.0-0.1
- Add the initial repository packaging changelog.
