# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate weezl
%global source_sha256 d4ca08e5ef825b65b056d9efbd95c8750683f0a6d0466d02e96dc2e4e360f3d2

Name:           rust-weezl0.2
Version:        0.2.1
Release:        0.3%{?dist}
Summary:        Fast LZW compression and decompression

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/weezl
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: remove benchmark-only targets and development dependencies.
# Not submitted upstream because crates.io library builds omit that surface.
Patch0:         weezl-remove-benchmarks.diff
# Fedora-specific: replace a test fixture omitted from the crates.io archive
# with equivalent data generated by the library encoder. Not submitted upstream
# because the upstream repository contains the original benchmark fixture.
Patch1:         weezl-fix-missing-test-fixture.diff
# Fedora-specific: replace a unit-test input removed by %%cargo_prep with the
# packaged Cargo manifest. Not submitted upstream because upstream does not use
# Fedora's lockfile-removing preparation macro.
Patch2:         weezl-fix-cargo-prep-test-input.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Fast LZW compression and decompression.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/Changes.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-devel %{_description}

This package contains library source intended for building other packages which
use the "futures" feature of the "%{crate}" crate.

%files       -n %{name}+futures-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.1-0.3
- Replace the Cargo.lock unit-test input removed by Fedora cargo preparation.

* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.2.1-0.2
- Enable configured SCM publication from the immutable crates.io source.
- Split benchmark metadata removal from the missing-fixture test repair.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.2.1-0.1
- Add the initial repository packaging changelog.
