# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate hayro-jbig2
%global source_sha256 69374b3668dd45aeb3d3145cda68f2c7b4f223aaa2511e67d076f1c7d741388d

Name:           rust-hayro-jbig2_0.3
Version:        0.3.0
Release:        0.2%{?dist}
Summary:        Memory-safe, pure-Rust JBIG2 decoder

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/hayro-jbig2
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Fedora-specific: remove benchmark/progress-only development dependencies that
# are not needed for the selected library tests. Not submitted upstream because
# this is a distribution test-dependency selection.
Patch0:         hayro-jbig2-fix-metadata.diff
# Fedora-specific: omit optional fearless_simd acceleration, which has no
# selected Fedora provider, while preserving the scalar std/image default path.
# Not submitted upstream because this is a distribution dependency selection.
Patch1:         hayro-jbig2-f43-no-fearless-simd.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A memory-safe, pure-Rust JBIG2 decoder.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.3.0-0.2
- Enable configured SCM publication with the scalar Fedora feature surface.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.3.0-0.1
- Add the initial repository packaging changelog.
