name: rust-strict0.2
status: enabled
blockers: []
upstream:
  provider: crates_io
  crate: strict
  version_requirement: = 0.2.0
  current_version: 0.2.0
  source_url_template: https://static.crates.io/crates/strict/strict-{version}.crate
  source_sha256: f42444fea5b87a39db4218d9422087e66a85d0e7a0963a439b07bcdf91804006
copr:
  enabled: true
  subdir: packages/rust-strict0.2
  spec: rust-strict0.2.spec
