# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate simba
%global source_sha256 8f45c644a9f3a386f9288625d9f0c1e999e1acf07a37df35d0516c7f199d9cb2

Name:           rust-simba0.10
Version:        0.10.0
Release:        0.2%{?dist}
Summary:        SIMD algebra for Rust

License:        Apache-2.0
URL:            https://crates.io/crates/simba
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Limit this compatibility package to the base/default/std surface needed by
#   nalgebra. The internal optional wide feature remains hidden because std
#   activates it transitively.
Patch:          simba-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
SIMD algebra for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n -f std

%build
%cargo_build -n -f std

%install
%cargo_install -n -f std

%if %{with check}
%check
%cargo_test -n -f std
%endif

%changelog
* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 0.10.0-0.2
- Initial Fedora 44 compatibility package
