# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate mail-parser
%global source_sha256 47785d444be4d32c1709171c6219a90f667c0ad0ffe68b4b179e794f31f4f9e8

Name:           rust-mail-parser0.11
Version:        0.11.5
Release:        0.1%{?dist}
Summary:        Fast and robust e-mail parsing library for Rust

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/mail-parser
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fast and robust e-mail parsing library for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/resources/eml/legacy/COPYING
%license %{crate_instdir}/resources/eml/malformed/COPYING
%license %{crate_instdir}/resources/eml/thirdparty/COPYING
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding_rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding_rs-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding_rs" feature of the "%{crate}" crate.

%files       -n %{name}+encoding_rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full_encoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full_encoding-devel %{_description}

This package contains library source intended for building other packages which
use the "full_encoding" feature of the "%{crate}" crate.

%files       -n %{name}+full_encoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f serde

%build
%cargo_build -f serde

%install
%cargo_install -f serde

%if %{with check}
%check
# The published JSON corpus differs for one serde-derived third-party fixture.
# Keep the test source, but exclude only that fixture comparison from %check.
%cargo_test -f serde -- -- --skip parsers::message::tests::parse_full_messages
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.11.5-0.1
- Add the initial repository packaging changelog.
