# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate dbase
%global source_sha256 abde818b4b82df61e01348c2b4610c221bcecb97cb7f567da086edf295d8d126

Name:           rust-dbase0.8
Version:        0.8.0
Release:        0.2%{?dist}
Summary:        Read and write database table files in Rust

License:        MIT
URL:            https://crates.io/crates/dbase
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Read and write database table files in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/Resources.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+datafusion-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+datafusion-devel %{_description}

This package contains library source intended for building other packages which
use the "datafusion" feature of the "%{crate}" crate.

%files       -n %{name}+datafusion-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding_rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding_rs-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding_rs" feature of the "%{crate}" crate.

%files       -n %{name}+encoding_rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+yore-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yore-devel %{_description}

This package contains library source intended for building other packages which
use the "yore" feature of the "%{crate}" crate.

%files       -n %{name}+yore-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 18 2026 Marcin FM <marcin@lgic.pl> - 0.8.0-0.2
- Enable configured SCM publication from the immutable crates.io source.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 0.8.0-0.1
- Add the initial changelog and clarify the database format wording.
