# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate tree-sitter-language-pack
%global source_sha256 f860e7a7df78207ed80a1f8a4cab7fd5e366ed9bfd5fa74f2d1ed3022905a058

Name:           rust-tree-sitter-language-pack1
Version:        1.12.5
Release:        0.1%{?dist}
Summary:        Core library for a source-built, licensed tree-sitter parser subset

License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND ISC AND MIT AND Unlicense AND WTFPL
URL:            https://crates.io/crates/tree-sitter-language-pack
Source:         %{crates_source}
Source1:        parser-sources-1.12.5-licensed-subset.tar.zst
# Remove benchmark-only and WASM-only dependencies from generated metadata.
# Fedora-specific; not submitted upstream because it selects the packaged native build graph.
Patch:          tree-sitter-language-pack-fix-metadata-auto.diff
# Use the packaged parser subset and disable runtime parser downloads.
# Fedora-specific; not submitted upstream because it integrates RPM-owned offline sources.
Patch1:         tree-sitter-language-pack-fedora-offline.patch
# Align the test dependency with Fedora's packaged insta release.
# Fedora-specific; not submitted upstream because it supports Fedora's crate version.
Patch2:         tree-sitter-language-pack-relax-insta.patch
# Expose every definition from the packaged static parser subset.
# Fedora-specific; not submitted upstream because it selects the audited RPM parser payload.
Patch3:         tree-sitter-language-pack-fedora-static-subset.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  util-linux-core

%global _description %{expand:
Core library for a source-built, licensed tree-sitter parser subset.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{_defaultlicensedir}/%{name}
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+config-devel %{_description}

This package contains library source intended for building other packages which
use the "config" feature of the "%{crate}" crate.

%files       -n %{name}+config-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+download-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+download-devel %{_description}

This package contains library source intended for building other packages which
use the "download" feature of the "%{crate}" crate.

%files       -n %{name}+download-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dynamic-loading-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dynamic-loading-devel %{_description}

This package contains library source intended for building other packages which
use the "dynamic-loading" feature of the "%{crate}" crate.

%files       -n %{name}+dynamic-loading-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-internals-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-internals-devel %{_description}

This package contains library source intended for building other packages which
use the "test-internals" feature of the "%{crate}" crate.

%files       -n %{name}+test-internals-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1 -a 1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f download,dynamic-loading,serde,config

%build
TSLP_LINK_MODE=static TSLP_OFFLINE=1 \
  TSLP_PARSER_SOURCE_DIR=%{_builddir}/parsers \
  %cargo_build -f download,dynamic-loading,serde,config

%install
rm -f parsers/angular/src/html.scanner.c \
  parsers/angular/src/html.tag.h \
  parsers/angular/src/tree_sitter/html.parser.h \
  parsers/bibtex/queries/locals.scm \
  parsers/bibtex/queries/tags.scm \
  parsers/haxe/queries/tags.scm \
  parsers/openscad/queries/injections.scm
%cargo_install
rm -rf %{buildroot}%{crate_instdir}/LICENSES \
  %{buildroot}%{crate_instdir}/license-evidence
install -d %{buildroot}%{_defaultlicensedir}/%{name}
cp -a LICENSES/. %{buildroot}%{_defaultlicensedir}/%{name}/
/usr/bin/hardlink -cv %{buildroot}%{crate_instdir}
/usr/bin/hardlink -cv %{buildroot}%{_defaultlicensedir}/%{name}

%if %{with check}
%check
TSLP_LINK_MODE=static TSLP_OFFLINE=1 \
  TSLP_PARSER_SOURCE_DIR=%{_builddir}/parsers \
  %__cargo test %{__cargo_common_opts} --profile rpm --no-fail-fast \
    --features download,dynamic-loading,serde,config --test parsing
TSLP_LINK_MODE=static TSLP_OFFLINE=1 \
  TSLP_PARSER_SOURCE_DIR=%{_builddir}/parsers \
  %__cargo test %{__cargo_common_opts} --profile rpm --no-fail-fast \
    --features download,dynamic-loading,serde,config --test kdl_repro
TSLP_LINK_MODE=static TSLP_OFFLINE=1 \
  TSLP_PARSER_SOURCE_DIR=%{_builddir}/parsers \
  %__cargo test %{__cargo_common_opts} --profile rpm --no-fail-fast \
    --features download,dynamic-loading,serde,config --test wire_format
%endif

%changelog
* Thu Jul 16 2026 Marcin FM <marcin@lgic.pl> - 1.12.5-0.1
- Build the audited source-only licensed parser subset offline without
  duplicating payload bytes while preserving every parser and license path.
