status: enabled
name: rust-fast_image_resize6
blockers: []
upstream:
  provider: crates_io
  crate: fast_image_resize
  version_requirement: = 6.0.0
  current_version: 6.0.0
  source_url_template: https://static.crates.io/crates/fast_image_resize/fast_image_resize-{version}.crate
  source_sha256: 12dd43e5011e8d8411a3215a0d57a2ec5c68282fb90eb5d7221fab0113442174
copr:
  enabled: true
  subdir: packages/rust-fast_image_resize6
  spec: rust-fast_image_resize6.spec
