# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate fast_image_resize
%global source_sha256 12dd43e5011e8d8411a3215a0d57a2ec5c68282fb90eb5d7221fab0113442174

Name:           rust-fast_image_resize6
Version:        6.0.0
Release:        0.4%{?dist}
Summary:        Library for fast image resizing with using of SIMD instructions

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/fast_image_resize
Source:         https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# Prune benchmark/reference-comparison dependencies and metadata unused by the packaged library tests.
# Fedora-specific; not submitted because upstream intentionally retains the benchmark comparison suite.
Patch:          fast_image_resize-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for fast image resizing with using of SIMD instructions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/benchmarks-arm64.md
%doc %{crate_instdir}/benchmarks-wasm32.md
%doc %{crate_instdir}/benchmarks-x86_64.md
%doc %{crate_instdir}/dev.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytemuck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytemuck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytemuck" feature of the "%{crate}" crate.

%files       -n %{name}+bytemuck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+for_testing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+for_testing-devel %{_description}

This package contains library source intended for building other packages which
use the "for_testing" feature of the "%{crate}" crate.

%files       -n %{name}+for_testing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_std-devel %{_description}

This package contains library source intended for building other packages which
use the "no_std" feature of the "%{crate}" crate.

%files       -n %{name}+no_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+only_u8x4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+only_u8x4-devel %{_description}

This package contains library source intended for building other packages which
use the "only_u8x4" feature of the "%{crate}" crate.

%files       -n %{name}+only_u8x4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f for_testing

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# Upstream's excluded data/ image fixtures have no redistribution-license
# evidence. Run every unit, integration, and doctest that does not read them.
%cargo_test -f for_testing -- --lib
%cargo_test -f for_testing -- --test alpha_tests
%cargo_test -f for_testing -- --test color_tests
%cargo_test -f for_testing -- --test image_view
%cargo_test -f for_testing -- --test images_tests -- --skip support_of_image_crate::use_dynamic_image --skip support_of_image_crate::use_image_buffer
%cargo_test -f for_testing -- --test resize_tests -- resize_to_same_size --exact
%cargo_test -f for_testing -- --test resize_tests -- resize_to_same_size_after_cropping --exact
%cargo_test -f for_testing -- --test resize_tests -- resize_to_same_width_or_height_after_cropping --exact
%cargo_test -f for_testing -- --test resize_tests -- not_u8x4::fractional_cropping --exact
%cargo_test -f for_testing -- --test resize_tests -- u8x4::invalid_crop_box --exact
%cargo_test -f for_testing -- --doc -- --skip 'src/lib.rs - (line 152)' --skip 'src/lib.rs - (line 197)'
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 6.0.0-0.4
- Omit unlicensed image fixtures and retain fixture-free tests.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 6.0.0-0.3
- Run the fixture-aware test selection through Fedora's Cargo test macro.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 6.0.0-0.2
- Document the benchmark and reference-comparison dependency-pruning patch.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 6.0.0-0.1
- Add the initial repository packaging changelog.
