# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate html-to-markdown-rs
%global source_sha256 c5b47de513bfcc3312a7521bd52ca1a287b0f85614d839c23b9873ff5c1465b7

Name:           rust-html-to-markdown-rs3
Version:        3.8.3
Release:        0.1%{?dist}
Summary:        High-performance HTML to Markdown converter

License:        MIT
URL:            https://crates.io/crates/html-to-markdown-rs
Source:         %{crates_source}
Patch:          html-to-markdown-rs-fedora-crates.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
High-performance converter from HTML to Markdown.
Part of the Xberg ecosystem.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+inline-images-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+inline-images-devel %{_description}

This package contains library source intended for building other packages which
use the "inline-images" feature of the "%{crate}" crate.

%files       -n %{name}+inline-images-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mcp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mcp-devel %{_description}

This package contains library source intended for building other packages which
use the "mcp" feature of the "%{crate}" crate.

%files       -n %{name}+mcp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mcp-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mcp-http-devel %{_description}

This package contains library source intended for building other packages which
use the "mcp-http" feature of the "%{crate}" crate.

%files       -n %{name}+mcp-http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+metadata-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+metadata-devel %{_description}

This package contains library source intended for building other packages which
use the "metadata" feature of the "%{crate}" crate.

%files       -n %{name}+metadata-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testkit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testkit-devel %{_description}

This package contains library source intended for building other packages which
use the "testkit" feature of the "%{crate}" crate.

%files       -n %{name}+testkit-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+visitor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+visitor-devel %{_description}

This package contains library source intended for building other packages which
use the "visitor" feature of the "%{crate}" crate.

%files       -n %{name}+visitor-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f inline-images,testkit

%build
%cargo_build -f inline-images,testkit

%install
%cargo_install -f inline-images,testkit

%if %{with check}
%check
# The published crate omits the repository-level CommonMark JSON corpus.
# Keep the test source, but exclude only that fixture-dependent target.
%cargo_test -f inline-images,testkit -- -- --skip commonmark_compliance_test
%endif

%changelog
* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 3.8.3-0.1
- Avoid implementation-specific terminology in package metadata.
