# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate html-to-markdown-rs
%global source_sha256 c5b47de513bfcc3312a7521bd52ca1a287b0f85614d839c23b9873ff5c1465b7
%global license_commit 41376152bb4a24ec53788a7c6537d75afb5360f4
%global license_sha256 c63dc76a907b2511aed2745a09c36d5533df1d519c93622f2721b236a72743b7

Name:           rust-html-to-markdown-rs3
Version:        3.8.3
Release:        0.2%{?dist}
Summary:        High-performance HTML to Markdown converter

License:        MIT
URL:            https://crates.io/crates/html-to-markdown-rs
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
# The crate archive omits the workspace-root license text; pin the release commit.
Source1:        https://raw.githubusercontent.com/xberg-io/html-to-markdown/%{license_commit}/LICENSE#/%{crate}-%{version}-LICENSE
# Fedora compatibility: lower only the regex minimum to Fedora's compatible 1.12.4 branch.
# Not submitted upstream because upstream intentionally raised its workspace dependency in commit 7c9073049c0c02770ba6e4fbd331c3a23d7f8b3.
Patch0:         html-to-markdown-rs-regex-fedora.diff
# Fedora test selection: omit only 11 targets whose workspace fixture corpora are absent from the published crate.
# Not submitted upstream because the complete upstream workspace includes and tests those fixtures.
Patch1:         html-to-markdown-rs-missing-fixtures.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
High-performance converter from HTML to Markdown.
Part of the Xberg ecosystem.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+inline-images-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+inline-images-devel %{_description}

This package contains library source intended for building other packages which
use the "inline-images" feature of the "%{crate}" crate.

%files       -n %{name}+inline-images-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mcp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mcp-devel %{_description}

This package contains library source intended for building other packages which
use the "mcp" feature of the "%{crate}" crate.

%files       -n %{name}+mcp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mcp-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mcp-http-devel %{_description}

This package contains library source intended for building other packages which
use the "mcp-http" feature of the "%{crate}" crate.

%files       -n %{name}+mcp-http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+metadata-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+metadata-devel %{_description}

This package contains library source intended for building other packages which
use the "metadata" feature of the "%{crate}" crate.

%files       -n %{name}+metadata-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testkit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testkit-devel %{_description}

This package contains library source intended for building other packages which
use the "testkit" feature of the "%{crate}" crate.

%files       -n %{name}+testkit-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+visitor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+visitor-devel %{_description}

This package contains library source intended for building other packages which
use the "visitor" feature of the "%{crate}" crate.

%files       -n %{name}+visitor-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
echo "%{source_sha256}  %{SOURCE0}" | sha256sum -c -
echo "%{license_sha256}  %{SOURCE1}" | sha256sum -c -
%autosetup -n %{crate}-%{version} -p1
install -pm0644 %{SOURCE1} LICENSE
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f testkit

%build
%cargo_build -f testkit

%install
%cargo_install -f testkit

%if %{with check}
%check
%cargo_test -f testkit
%endif

%changelog
* Sun Jul 19 2026 Marcin FM <marcin@lgic.pl> - 3.8.3-0.2
- Enable the default metadata feature with exact license and fixture accounting.

* Fri Jul 17 2026 Marcin FM <marcin@lgic.pl> - 3.8.3-0.1
- Avoid implementation-specific terminology in package metadata.
